CREATE TABLE [dbo].[T_CUSTOMER_PHONE]
(
	[LINK_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [CUSTOMER_ID] INT NOT NULL, 
    [PHONE_NUMBER] VARCHAR(15) NOT NULL, /* actual phone number */
    CONSTRAINT [UQ_COMBINED_DATA] UNIQUE NONCLUSTERED
    (
        [CUSTOMER_ID], [PHONE_NUMBER]
    ), 
    CONSTRAINT [FK_T_CUSTOMER_PHONE_ToCustomer] FOREIGN KEY ([CUSTOMER_ID]) REFERENCES [T_CUSTOMER]([CUSTOMER_ID])
)
