CREATE TABLE [dbo].[T_ITEM_RATE]
(
	[RATE_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [RATE_TYPE] NVARCHAR(10) NOT NULL /* EUR/etc */, 
    [BY_SECOND] MONEY NOT NULL, 
    [ITEM_ID] INT NOT NULL, 
    CONSTRAINT [FK_T_ITEM_RATE_ToRentalItem] FOREIGN KEY ([ITEM_ID]) REFERENCES [T_RENTAL_ITEM]([ITEM_ID])
)
