CREATE TABLE [dbo].[T_REGISTRATION_QUEUE]
(
	[ITEM_ID] INT NOT NULL, 
    [CREATED] DATETIME2 NOT NULL, 
    [CUSTOMER_ID] INT NOT NULL, 
    CONSTRAINT [FK_T_REGISTRATION_QUEUE_ToRentalItem] FOREIGN KEY ([ITEM_ID]) REFERENCES [T_RENTAL_ITEM]([ITEM_ID]),
    CONSTRAINT [UQ_COMBINED_DATA2] UNIQUE NONCLUSTERED
    (
        [ITEM_ID], [CUSTOMER_ID]
    ), 
)
