CREATE TABLE [dbo].[T_RENTAL_ITEM]
(
	[ITEM_ID] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ITEM_TYPE_ID] INT NOT NULL, 
    [ITEM_NAME] NVARCHAR(100) NOT NULL, 
    CONSTRAINT [FK_T_RENTAL_ITEM_ToRentalType] FOREIGN KEY ([ITEM_TYPE_ID]) REFERENCES [T_RENTAL_ITEM_TYPE]([TYPE_ID]) 
)
